server.port=8081

spring.data.mongodb.uri=mongodb+srv://sudhanshuc16_db_user:Sudhanshu%40711@blogproject.gzevhcg.mongodb.net/blog_portal?retryWrites=true&w=majority
spring.data.mongodb.database=blog_portal


logging.level.com.logging=info
logging.file.name=src/loggers/appLog.log
logging.pattern.file= %d [%level] %c [%t] %m %n
logging.pattern.console= %d [%level] %c [%t] %m %n
